name: Deploy

# Controls when the action will run
on:
  push:
    branches:
      - main  # Triggers the workflow on a push to the "main" branch
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code from your repository

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master  # Uses appleboy SSH action to deploy
        with:
          host: ${{ secrets.HOST }}  # Fetches the HOST secret from GitHub secrets
          username: ${{ secrets.USERNAME }}  # Fetches the USERNAME secret
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Fetches the SSH private key from secrets
          port: 22  # Default SSH port
          script: |
            cd /var/www/youtubetutorial.com/
            git pull origin main  # Pulls the latest code from the main branch
            git status  # Displays the git status of the working directory
            npm install --only=prod  # Installs production dependencies
