name: Last

# Controls when the action will run
on:
  push:
    branches:
      - main  # Trigger this action on push to the "main" branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH and deploy using appleboy/ssh-action
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}  # Fetch the host from secrets
          username: ${{ secrets.USERNAME }}  # Fetch the username from secrets
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Fetch the SSH private key from secrets
          port: 22  # Default SSH port
          script: |
           
            npm install --only=prod
            
            # Start the application using npm start
            npm start
