name: Deploy to VM

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$VM_PRIVATE_KEY" > ~/.ssh/id_rsa  # Add private key from GitHub secrets
        chmod 600 ~/.ssh/id_rsa  # Secure the private key
        ssh-keyscan -t rsa your-vm-ip >> ~/.ssh/known_hosts  # Add your VM’s SSH key to known hosts

    - name: Deploy to VM
      run: |
        # Replace 'your-user' and 'your-vm-ip' with your actual username and VM IP address
        ssh -o StrictHostKeyChecking=no your-user@your-vm-ip "
          cd /path/to/your/app && \
          git pull origin main && \
          npm install && \
          npm run build && \
          pm2 restart your-app-name || pm2 start npm --name 'your-app-name' -- run start
        "
      env:
        VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}  # Reference the secret for the private SSH key
