name: Deploy Node.js App to VM

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the GitHub Actions environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from your repository

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$VM_PRIVATE_KEY" > ~/.ssh/id_rsa  # Add private key from GitHub secrets
        chmod 600 ~/.ssh/id_rsa  # Secure the private key
        
        # Add the VM's public key to known_hosts, skipping on failure
        ssh-keyscan -t rsa 51.79.106.176 >> ~/.ssh/known_hosts || echo "ssh-keyscan failed, continuing..."

    - name: Test SSH Connection
      run: |
        # Test SSH connection to the VM to ensure the connection works before deployment
        ssh -o StrictHostKeyChecking=no nodetestcustomde@51.79.106.176 "echo SSH connection successful!"

    - name: Deploy to VM
      run: |
        # SSH into the VM and deploy the app
        ssh -o StrictHostKeyChecking=no nodetestcustomde@51.79.106.176 "
          cd /path/to/your/app && \
          echo 'Pulling the latest code from main...' && \
          git pull origin main && \
          echo 'Installing dependencies...' && \
          npm install && \
          echo 'Building the app...' && \
          npm run build && \
          echo 'Restarting the app with pm2...' && \
          pm2 restart your-app || pm2 start npm --name 'your-app' -- run start
        "
      env:
        VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}  # Reference the private key secret from GitHub
