jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH and deploy app
      run: |
        # Install sshpass for non-interactive SSH login using password
        sudo apt-get update
        sudo apt-get install sshpass -y
        
        # Set up SSH login credentials
        export SSH_USERNAME="nodetestcustomde"  # VM username
        export SSH_PASSWORD="${{ secrets.VM_PASSWORD }}"  # VM password stored in secrets
        export SERVER_IP="54.39.100.44"  # VM IP address

        # SSH into the VM and deploy the app
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SERVER_IP "
          cd /path/to/your/app && \
          git pull origin main && \
          npm install && \
          npm run build && \
          pm2 restart your-app || pm2 start npm --name 'your-app' -- run start
        "
      env:
        VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
